## Registration Controller
harcam_triatlon_signup:
    pattern:    /signup
    defaults:   { _controller: HarcamTriatlonBundle:Registration:signup }
    methods:    [GET]

harcam_triatlon_signup_process:
    pattern:    /signup
    defaults:   { _controller: HarcamTriatlonBundle:Registration:signupProcess }
    methods:    [POST]

harcam_triatlon_signup_success:
    pattern:    /signup/success
    defaults:   { _controller: HarcamTriatlonBundle:Registration:signupSuccess }

## Page Controller
harcam_triatlon_home:
    pattern:    /
    defaults:   { _controller: HarcamTriatlonBundle:Page:home }

harcam_triatlon_page:
    pattern:    /{page}
    defaults:   { _controller: HarcamTriatlonBundle:Page:page }