## SECURITY
login:
    pattern:    /admin/login
    defaults:   { _controller: HarcamTriatlonBundle:Security:login }

login_check:
    pattern:    /admin/login_check

logout:
    pattern:    /admin/logout

## Admin Controller
harcam_triatlon_admin_client_list:
    pattern:    /admin/
    defaults:   { _controller: HarcamTriatlonBundle:Admin:viewClients }

harcam_triatlon_admin_client_view:
    pattern:    /admin/client/{id}
    defaults:   { _controller: HarcamTriatlonBundle:Admin:view }

harcam_triatlon_admin_client_delete:
    pattern:    /admin/client/{id}/delete
    defaults:   { _controller: HarcamTriatlonBundle:Admin:delete }
    methods:    [POST]
    
harcam_triatlon_admin_client_changepaymentstatus:
    pattern:    /admin/client/{id}/changepaymentstatus
    defaults:   { _controller: HarcamTriatlonBundle:Admin: }
    methods:    [POST]
    
## Registration Controller
harcam_triatlon_signup:
    pattern:    /signup
    defaults:   { _controller: HarcamTriatlonBundle:Registration:signup }
    methods:    [GET]

harcam_triatlon_signup_process:
    pattern:    /signup
    defaults:   { _controller: HarcamTriatlonBundle:Registration:signupProcess }
    methods:    [POST]

harcam_triatlon_signup_success:
    pattern:    /signup/success
    defaults:   { _controller: HarcamTriatlonBundle:Registration:signupSuccess }

harcam_triatlon_signup_payment:
    pattern:    /signup/payment/{email}/{token}
    defaults:   { _controller: HarcamTriatlonBundle:Registration:payment }

harcam_triatlon_signup_payment_success:
    pattern:    /signup/payment/success
    defaults:   { _controller: HarcamTriatlonBundle:Registration:paymentSuccess }

## Page Controller
harcam_triatlon_home:
    pattern:    /
    defaults:   { _controller: HarcamTriatlonBundle:Page:home }

harcam_triatlon_page:
    pattern:    /{page}
    defaults:   { _controller: HarcamTriatlonBundle:Page:page }