## Page Controller
harcam_triatlon_home:
    pattern:    /
    defaults:   { _controller: HarcamTriatlonBundle:Page:home }

harcam_triatlon_page:
    pattern:    /p/{page}
    defaults:   { _controller: HarcamTriatlonBundle:Page:page }

## Registration Controller
harcam_triatlon_signup:
    pattern:    /signup
    defaults:   { _controller: HarcamTriatlonController:Registration:signup }
    methods:    [GET]

harcam_triatlon_signup_process:
    pattern:    /signup
    defaults:   { _controller: HarcamTriatlonController:Registration:signupProcess }
    methods:    [POST]